# -*- coding: utf-8 -*-
"""automate_GilangPutraFirmansyah

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131FCqznbVmrhOyON9Yqi-DnnbGIarwsb
"""

import pandas as pd
import os
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer


def preprocess_data(
    input_path: str, output_dir: str, test_size: float = 0.2, random_state: int = 42
):
    df = pd.read_excel(input_path, sheet_name="Data", skiprows=1, engine="xlrd")

    df = df.drop(columns=["ID"])

    target_col = "default payment next month"
    X = df.drop(columns=[target_col])
    y = df[target_col]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=y
    )

    imputer = SimpleImputer(strategy="median")
    X_train_imputed = imputer.fit_transform(X_train)
    X_test_imputed = imputer.transform(X_test)

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train_imputed)
    X_test_scaled = scaler.transform(X_test_imputed)

    os.makedirs(output_dir, exist_ok=True)

    pd.DataFrame(X_train_scaled, columns=X.columns).to_csv(
        f"{output_dir}/X_train.csv", index=False
    )
    pd.DataFrame(X_test_scaled, columns=X.columns).to_csv(
        f"{output_dir}/X_test.csv", index=False
    )
    y_train.to_csv(f"{output_dir}/y_train.csv", index=False)
    y_test.to_csv(f"{output_dir}/y_test.csv", index=False)

    joblib.dump(imputer, f"{output_dir}/imputer.joblib")
    joblib.dump(scaler, f"{output_dir}/scaler.joblib")

    print("Preprocessing selesai. Dataset siap dilatih.")


if __name__ == "__main__":
    preprocess_data(
        input_path="../CreditCardDefaultDataset_raw/default of credit card clients.xls",
        output_dir="./CreditCardDefaultDataset_preprocessing",
    )
