name: MLflow Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training (MLflow)
      run: |
        mlflow run . --env-manager=local

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
          -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image from MLflow model
      run: |
        mlflow models build-docker \
          -m runs:/$(ls mlruns/0 | head -n 1)/model \
          -n ${{ secrets.DOCKERHUB_USERNAME }}/creditcard-mlflow

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/creditcard-mlflow
