name: MLflow CI Pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MLflow
        run: |
          pip install mlflow scikit-learn pandas

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_URI: file:${{ github.workspace }}/MLProject/mlruns
        run: |
          mlflow run MLProject --env-manager=local
